In [1]:
import pandas as pd

### Unificamos en un dataset los de 2015/2016,2016/2017,2017/2018,2018/2019

In [2]:
dataset_Temporada_2015_2016 =  pd.read_csv(r"season-1516_csv.csv",sep=",");
dataset_Temporada_2016_2017 =  pd.read_csv(r"season-1617_csv.csv",sep=",");
dataset_Temporada_2017_2018 =  pd.read_csv(r"season-1718_csv.csv",sep=",");
dataset_Temporada_2018_2019 =  pd.read_csv(r"season-1819_csv.csv",sep=";",);

df1 = pd.DataFrame(dataset_Temporada_2015_2016)
df2 = pd.DataFrame(dataset_Temporada_2016_2017)
df3 = pd.DataFrame(dataset_Temporada_2017_2018)
df4 = pd.DataFrame(dataset_Temporada_2018_2019)
df1['Temporada']='2015/2016'
df2['Temporada']='2016/2017'
df3['Temporada']='2017/2018'
df4['Temporada']='2018/2019'

In [3]:
frames = [df1,df2,df3,df4]
dataset_definitivo_2015_2019 = pd.concat(frames)
dataset_definitivo_2015_2019

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA,Temporada,"Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,Bb1X2,BbMxH,BbAvH,BbMxD,BbAvD,BbMxA,BbAvA,BbOU,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA"
0,SP1,21/08/15,Malaga,Sevilla,0.0,0.0,D,0.0,0.0,D,...,0.25,2.02,1.95,1.94,1.90,3.22,3.50,2.36,2015/2016,NaN
1,SP1,22/08/15,Ath Madrid,Las Palmas,1.0,0.0,H,1.0,0.0,H,...,-1.75,2.02,1.95,1.95,1.89,1.25,6.24,16.90,2015/2016,NaN
2,SP1,22/08/15,Espanol,Getafe,1.0,0.0,H,1.0,0.0,H,...,-0.50,1.95,1.90,2.01,1.94,2.10,3.28,4.19,2015/2016,NaN
3,SP1,22/08/15,La Coruna,Sociedad,0.0,0.0,D,0.0,0.0,D,...,0.00,1.82,1.78,2.15,2.07,2.44,3.41,3.15,2015/2016,NaN
4,SP1,22/08/15,Vallecano,Valencia,0.0,0.0,D,0.0,0.0,D,...,0.50,1.90,1.83,2.08,2.01,2.93,3.68,2.46,2015/2016,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018/2019,"SP1,18/05/2019,Levante,Ath Madrid,2,2,D,2,0,H,..."
376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018/2019,"SP1,18/05/2019,Sevilla,Ath Bilbao,2,0,H,1,0,H,..."
377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018/2019,"SP1,18/05/2019,Valladolid,Valencia,0,2,A,0,1,A..."
378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018/2019,"SP1,19/05/2019,Eibar,Barcelona,2,2,D,2,2,D,15,..."
379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018/2019,"SP1,19/05/2019,Real Madrid,Betis,0,2,A,0,0,D,9..."


### Actualizamos los nombres de los equipos tanto locales como visitantes de las temporadas 2015/2016,2016/2017,2017/2018,2018/2019

In [4]:
dataset_definitivo_2015_2019['HomeTeam'].unique().tolist()

['Malaga',
 'Ath Madrid',
 'Espanol',
 'La Coruna',
 'Vallecano',
 'Ath Bilbao',
 'Betis',
 'Levante',
 'Sp Gijon',
 'Granada',
 'Villarreal',
 'Barcelona',
 'Celta',
 'Real Madrid',
 'Sociedad',
 'Eibar',
 'Getafe',
 'Las Palmas',
 'Sevilla',
 'Valencia',
 'Leganes',
 'Osasuna',
 'Alaves',
 'Girona',
 nan]

In [5]:
dataset_definitivo_2015_2019['AwayTeam'].unique().tolist()

['Sevilla',
 'Las Palmas',
 'Getafe',
 'Sociedad',
 'Valencia',
 'Barcelona',
 'Villarreal',
 'Celta',
 'Real Madrid',
 'Eibar',
 'Espanol',
 'Malaga',
 'Vallecano',
 'Betis',
 'Sp Gijon',
 'Ath Bilbao',
 'Granada',
 'Levante',
 'Ath Madrid',
 'La Coruna',
 'Osasuna',
 'Alaves',
 'Leganes',
 'Girona',
 nan]

In [6]:
df = pd.DataFrame(data=dataset_definitivo_2015_2019)
df.HomeTeam.replace({"Malaga":"Málaga",'Ath Madrid':'Atlético','Espanol':'Espanyol',"La Coruna":"Deportivo","Vallecano":'Rayo',
"Ath Bilbao":'Athletic',"Sp Gijon":"Sporting",'Sociedad':'R. Sociedad',"Leganes":'Leganés',
'Alaves':"Alavés",'Valladolid':'Real Valladolid'},inplace=True)


df.AwayTeam.replace({"Malaga":"Málaga",'Ath Madrid':'Atlético','Espanol':'Espanyol',"La Coruna":"Deportivo","Vallecano":'Rayo',
"Ath Bilbao":'Athletic',"Sp Gijon":"Sporting",'Sociedad':'R. Sociedad',"Leganes":'Leganés',
'Alaves':"Alavés",'Valladolid':'Real Valladolid'},inplace=True)

In [7]:
dataset_definitivo_2015_2019

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA,Temporada,"Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,Bb1X2,BbMxH,BbAvH,BbMxD,BbAvD,BbMxA,BbAvA,BbOU,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA"
0,SP1,21/08/15,Málaga,Sevilla,0.0,0.0,D,0.0,0.0,D,...,0.25,2.02,1.95,1.94,1.90,3.22,3.50,2.36,2015/2016,NaN
1,SP1,22/08/15,Atlético,Las Palmas,1.0,0.0,H,1.0,0.0,H,...,-1.75,2.02,1.95,1.95,1.89,1.25,6.24,16.90,2015/2016,NaN
2,SP1,22/08/15,Espanyol,Getafe,1.0,0.0,H,1.0,0.0,H,...,-0.50,1.95,1.90,2.01,1.94,2.10,3.28,4.19,2015/2016,NaN
3,SP1,22/08/15,Deportivo,R. Sociedad,0.0,0.0,D,0.0,0.0,D,...,0.00,1.82,1.78,2.15,2.07,2.44,3.41,3.15,2015/2016,NaN
4,SP1,22/08/15,Rayo,Valencia,0.0,0.0,D,0.0,0.0,D,...,0.50,1.90,1.83,2.08,2.01,2.93,3.68,2.46,2015/2016,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018/2019,"SP1,18/05/2019,Levante,Ath Madrid,2,2,D,2,0,H,..."
376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018/2019,"SP1,18/05/2019,Sevilla,Ath Bilbao,2,0,H,1,0,H,..."
377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018/2019,"SP1,18/05/2019,Valladolid,Valencia,0,2,A,0,1,A..."
378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018/2019,"SP1,19/05/2019,Eibar,Barcelona,2,2,D,2,2,D,15,..."
379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018/2019,"SP1,19/05/2019,Real Madrid,Betis,0,2,A,0,0,D,9..."

In [8]:
dataset_definitivo_2015_2019.columns

Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY',
       'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH',
       'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD',
       'WHA', 'VCH', 'VCD', 'VCA', 'Bb1X2', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD',
       'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5',
       'BbAv<2.5', 'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA',
       'PSCH', 'PSCD', 'PSCA', 'Temporada',
       'Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,Bb1X2,BbMxH,BbAvH,BbMxD,BbAvD,BbMxA,BbAvA,BbOU,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA'],
      dtype='object')

### Borramos las columnas innecesarias

In [9]:
dataset_arreglado_2015_2019 = dataset_definitivo_2015_2019.drop(['Div',
       'HTHG', 'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC',
       'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA',
       'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH', 'PSD', 'PSA', 'WHH',
       'WHD', 'WHA', 'VCH', 'VCD', 'VCA', 'Bb1X2', 'BbMxH', 'BbAvH', 'BbMxD',
       'BbAvD', 'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5',
       'BbAv<2.5', 'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA',
       'PSCH', 'PSCD', 'PSCA'],axis=1)

### Renombramos algunas Columnas para entender mejor su significado

In [10]:
dataset_arreglado_2015_2019.rename(columns={"Date":"Fecha","HomeTeam":"Equipo_Local","AwayTeam":"Equipo_Visitante","FTHG":"Goles_Local","FTAG":"Goles_Visitante","FTR":"Resultado"},inplace=True)

### Calculamos los puntos Locales y los puntos Visitantes

In [11]:
dataset_arreglado_2015_2019.replace({'D':'x','H':'1','A':'2'},inplace=True)

In [12]:
dataset_arreglado_2015_2019['Puntos_Locales'] = dataset_arreglado_2015_2019['Resultado']

In [13]:
dataset_arreglado_2015_2019['Puntos_Visitantes'] = dataset_arreglado_2015_2019['Resultado']

In [14]:
dataset_arreglado_2015_2019['Puntos_Locales'].replace({'x':1,'1':3,'2':0},inplace=True)

In [15]:
dataset_arreglado_2015_2019['Puntos_Visitantes'].replace({'x':1,'1':0,'2':3},inplace=True)

In [16]:
dataset_arreglado_2015_2019.to_csv('dataset_auxiliar_Resultados_2015_2019.csv',index=False)

# Generación Datasets con Scrapping

"""
En esta sección se ha generado los datasets obtenidos con la Técnica de Web Scrapping
"""

In [17]:
import pandas as pd

In [18]:
import csv
from bs4 import BeautifulSoup
import urllib.request


def extraerJornadas_2019_2020():
    res = []
    url = "https://resultados.as.com/resultados/futbol/primera/2019_2020/calendario/" 
    fichero = urllib.request.urlopen(url)
    s = BeautifulSoup(fichero, "lxml")
    res += s.find_all("div", class_=["cont-modulo", "resultados"])
    return res




def cargar_datos_2019_2020():
    jornadas = extraerJornadas_2019_2020()
    lista_enlaces = []
    lista_jornadas = []
    lista_resultados = []
    lista_equipos_locales = []
    lista_equipos_visitantes = []
    for jornada in jornadas:
        jorn = jornada.find("h2").find("a").text
        lista_jornadas.append(jorn)
        enlacesPartidos = jornada.find("div", class_=["cont-resultados", "cf"]).find("table", class_="tabla-datos").find("tbody").find_all("tr")
        for enlace in enlacesPartidos:
            link = enlace.find("td", class_="col-resultado").find("a")["href"]
            resultado = enlace.find("td",class_="col-resultado finalizado").find("a").text
            equipo_local =  enlace.find("td", class_="col-equipo-local").find("a").find("span", class_="nombre-equipo").text
            equipo_visitante = enlace.find("td", class_="col-equipo-visitante").find("a").find("span", class_="nombre-equipo").text 
            lista_enlaces.append(link)
            lista_resultados.append(resultado)
            lista_equipos_locales.append(equipo_local)
            lista_equipos_visitantes.append(equipo_visitante)
    return lista_jornadas,lista_enlaces,lista_resultados,lista_equipos_locales,lista_equipos_visitantes  



def crear_csv_2019_2020():
    resultados= cargar_datos_2019_2020().__getitem__(2)
    equipoLocal=cargar_datos_2019_2020().__getitem__(3)
    equipoVisitante=cargar_datos_2019_2020().__getitem__(4)
    with open('dataset_Scraping_2019_2020.csv','wt')as csvfile: #Se puede sustituir para que se genere dónde haga falta/dataset3.csv','wt')as csvfile:   #Se puede sustituir para que se genere dónde haga falta
        writer = csv.writer(csvfile, delimiter=',', lineterminator='\n')
        writer.writerow(['Equipo_Local','Equipo_Visitante','Resultado'])  
        for eqLocal,eqVisit,result in zip(equipoLocal,equipoVisitante,resultados):
            writer.writerow([eqLocal,eqVisit,result])
            
extraerJornadas_2019_2020()
cargar_datos_2019_2020()
crear_csv_2019_2020()

In [19]:

import csv
from bs4 import BeautifulSoup
import urllib.request


def extraerJornadas_2020_2021():
    res = []
    url = "https://resultados.as.com/resultados/futbol/primera/2020_2021/calendario/" 
    fichero = urllib.request.urlopen(url)
    s = BeautifulSoup(fichero, "lxml")
    res += s.find_all("div", class_=["cont-modulo", "resultados"])
    #print(res)
    return res




def cargar_datos_2020_2021():
    jornadas = extraerJornadas_2020_2021()
    lista_enlaces = []
    lista_jornadas = []
    lista_resultados = []
    lista_equipos_locales = []
    lista_equipos_visitantes = []
    for jornada in jornadas:
        jorn = jornada.find("h2").find("a").text
        lista_jornadas.append(jorn)
        enlacesPartidos = jornada.find("div", class_=["cont-resultados", "cf"]).find("table", class_="tabla-datos").find("tbody").find_all("tr")
        for enlace in enlacesPartidos:
            link = enlace.find("td", class_="col-resultado").find("a")["href"]
            resultado = enlace.find("td",class_="col-resultado finalizado").find("a").text
            equipo_local =  enlace.find("td", class_="col-equipo-local").find("a").find("span", class_="nombre-equipo").text
            equipo_visitante = enlace.find("td", class_="col-equipo-visitante").find("a").find("span", class_="nombre-equipo").text 
            lista_enlaces.append(link)
            lista_resultados.append(resultado)
            lista_equipos_locales.append(equipo_local)
            lista_equipos_visitantes.append(equipo_visitante)
    return lista_jornadas,lista_enlaces,lista_resultados,lista_equipos_locales,lista_equipos_visitantes  




def crear_csv_2020_2021():
    resultados= cargar_datos_2020_2021().__getitem__(2)
    equipoLocal=cargar_datos_2020_2021().__getitem__(3)
    equipoVisitante=cargar_datos_2020_2021().__getitem__(4)
    with open('dataset_Scraping_2020_2021.csv','wt')as csvfile: #Se puede sustituir para que se genere dónde haga falta/dataset3.csv','wt')as csvfile:   #Se puede sustituir para que se genere dónde haga falta
        writer = csv.writer(csvfile, delimiter=',', lineterminator='\n')
        writer.writerow(['Equipo_Local','Equipo_Visitante','Resultado'])  
        for eqLocal,eqVisit,result in zip(equipoLocal,equipoVisitante,resultados):
            writer.writerow([eqLocal,eqVisit,result])
            
extraerJornadas_2020_2021()
cargar_datos_2020_2021()
crear_csv_2020_2021()

In [20]:
import csv
from bs4 import BeautifulSoup
import urllib.request


def extraerJornadas_2021_2022():
    res = []
    url = "https://resultados.as.com/resultados/futbol/primera/2021_2022/calendario/" 
    fichero = urllib.request.urlopen(url)
    s = BeautifulSoup(fichero, "lxml")
    res += s.find_all("div", class_=["cont-modulo", "resultados"])
    #print(res)
    return res




def cargar_datos_2021_2022():
    jornadas = extraerJornadas_2021_2022()
    lista_enlaces = []
    lista_jornadas = []
    lista_resultados = []
    lista_equipos_locales = []
    lista_equipos_visitantes = []
    for jornada in jornadas:
        jorn = jornada.find("h2").find("a").text
        lista_jornadas.append(jorn)
        enlacesPartidos = jornada.find("div", class_=["cont-resultados", "cf"]).find("table", class_="tabla-datos").find("tbody").find_all("tr")
        for enlace in enlacesPartidos:
            link = enlace.find("td", class_="col-resultado").find("a")["href"]
            resultado = enlace.find("td",class_="col-resultado finalizado").find("a").text
            equipo_local =  enlace.find("td", class_="col-equipo-local").find("a").find("span", class_="nombre-equipo").text
            equipo_visitante = enlace.find("td", class_="col-equipo-visitante").find("a").find("span", class_="nombre-equipo").text 
            lista_enlaces.append(link)
            lista_resultados.append(resultado)
            lista_equipos_locales.append(equipo_local)
            lista_equipos_visitantes.append(equipo_visitante)
    return lista_jornadas,lista_enlaces,lista_resultados,lista_equipos_locales,lista_equipos_visitantes  




def crear_csv_2021_2022():
    resultados= cargar_datos_2021_2022().__getitem__(2)
    equipoLocal=cargar_datos_2021_2022().__getitem__(3)
    equipoVisitante=cargar_datos_2021_2022().__getitem__(4)
    with open('dataset_Scraping_2021_2022.csv','wt')as csvfile: #Se puede sustituir para que se genere dónde haga falta/dataset3.csv','wt')as csvfile:   #Se puede sustituir para que se genere dónde haga falta
        writer = csv.writer(csvfile, delimiter=',', lineterminator='\n')
        writer.writerow(['Equipo_Local','Equipo_Visitante','Resultado'])  
        for eqLocal,eqVisit,result in zip(equipoLocal,equipoVisitante,resultados):
            writer.writerow([eqLocal,eqVisit,result])
            
extraerJornadas_2021_2022()
cargar_datos_2021_2022()
crear_csv_2021_2022()

### Unificamos en un dataset los datasets de la temporada 2019/2020, 2020/2021,2021/2022

In [21]:
dataset_Temporada_2019_2020 = pd.read_csv(r"dataset_Scraping_2019_2020.csv",sep=",",encoding="latin-1");
dataset_Temporada_2020_2021 = pd.read_csv(r"dataset_Scraping_2020_2021.csv",sep=",",encoding="latin-1");
dataset_Temporada_2021_2022 = pd.read_csv(r"dataset_Scraping_2021_2022.csv",sep=",",encoding="latin-1");

In [22]:
df4 = pd.DataFrame(dataset_Temporada_2019_2020)
df5 = pd.DataFrame(dataset_Temporada_2020_2021)
df6 = pd.DataFrame(dataset_Temporada_2021_2022)
df4['Temporada']='2019/2020'
df5['Temporada']='2020/2021'
df6['Temporada']='2021/2022'

In [23]:
frames = [df4,df5,df6]
dataset_definitivo_2020_2022 = pd.concat(frames)

In [24]:
dataset_definitivo_2020_2022['Goles_Local'] = dataset_definitivo_2020_2022['Resultado']

In [25]:
dataset_definitivo_2020_2022['Goles_Visitante'] = dataset_definitivo_2020_2022['Resultado']

In [26]:
dataset_definitivo_2020_2022

,Equipo_Local,Equipo_Visitante,Resultado,Temporada,Goles_Local,Goles_Visitante
0,Athletic,Barcelona,\r\n 1 - 0\r\n,2019/2020,\r\n 1 - 0\r\n,\r\n 1 - 0\r\n
1,Celta,Real Madrid,\r\n 1 - 3\r\n,2019/2020,\r\n 1 - 3\r\n,\r\n 1 - 3\r\n
2,Valencia,R. Sociedad,\r\n 1 - 1\r\n,2019/2020,\r\n 1 - 1\r\n,\r\n 1 - 1\r\n
3,Mallorca,Eibar,\r\n 2 - 1\r\n,2019/2020,\r\n 2 - 1\r\n,\r\n 2 - 1\r\n
4,Villarreal,Granada,\r\n 4 - 4\r\n,2019/2020,\r\n 4 - 4\r\n,\r\n 4 - 4\r\n
...,...,...,...,...,...,...
375,Granada,Espanyol,\r\n 0 - 0\r\n,2021/2022,\r\n 0 - 0\r\n,\r\n 0 - 0\r\n
376,Osasuna,Mallorca,\r\n 0 - 2\r\n,2021/2022,\r\n 0 - 2\r\n,\r\n 0 - 2\r\n
377,Barcelona,Villarreal,\r\n 0 - 2\r\n,2021/2022,\r\n 0 - 2\r\n,\r\n 0 - 2\r\n
378,R. Sociedad,Atlético,\r\n 1 - 2\r\n,2021/2022,\r\n 1 - 2\r\n,\r\n 1 - 2\r\n
379,Sevilla,Athletic,\r\n 1 - 0\r\n,2021/2022,\r\n 1 - 0\r\n,\r\n 1 - 0\r\n

### Actualizamos los valores de los goles locales y los goles Visitantes

In [27]:
dataset_definitivo_2020_2022['Goles_Local'].unique().tolist()

['\r\n        1 - 0\r\n        ',
 '\r\n        1 - 3\r\n        ',
 '\r\n        1 - 1\r\n        ',
 '\r\n        2 - 1\r\n        ',
 '\r\n        4 - 4\r\n        ',
 '\r\n        0 - 1\r\n        ',
 '\r\n        0 - 2\r\n        ',
 '\r\n        1 - 2\r\n        ',
 '\r\n        0 - 0\r\n        ',
 '\r\n        5 - 2\r\n        ',
 '\r\n        2 - 0\r\n        ',
 '\r\n        2 - 2\r\n        ',
 '\r\n        3 - 2\r\n        ',
 '\r\n        0 - 3\r\n        ',
 '\r\n        4 - 2\r\n        ',
 '\r\n        3 - 1\r\n        ',
 '\r\n        3 - 3\r\n        ',
 '\r\n        3 - 0\r\n        ',
 '\r\n        5 - 1\r\n        ',
 '\r\n        4 - 0\r\n        ',
 '\r\n        4 - 1\r\n        ',
 '\r\n        5 - 0\r\n        ',
 '\r\n        0 - 4\r\n        ',
 '\r\n        2 - 4\r\n        ',
 '\r\n        3 - 4\r\n        ',
 '\r\n        1 - 4\r\n        ',
 '\r\n        2 - 3\r\n        ',
 '\r\n        0 - 5\r\n        ',
 '\r\n        6 - 0\r\n        ',
 '\r\n        6 - 1\r\n        ',
 '\r\n        4 - 3\r\n        ',
 '\r\n        1 - 6\r\n        ',
 '\r\n        1 - 5\r\n        ',
 '\r\n        5 - 3\r\n        ',
 '\r\n        2 - 6\r\n        ']

In [28]:
dataset_definitivo_2020_2022['Goles_Local'] = dataset_definitivo_2020_2022['Goles_Local'].str.replace(",","").str.replace("\r\n","").str.replace(" ","").str.split("-")

In [29]:
lista = dataset_definitivo_2020_2022['Goles_Local'].tolist()
lista_goles_locales = []
for element in lista:
    gol_local="".join(map(str,element))[0]
    lista_goles_locales.append(gol_local)

In [30]:
dataset_definitivo_2020_2022['Goles_Local']=lista_goles_locales

In [31]:
dataset_definitivo_2020_2022['Goles_Visitante'].unique().tolist()

['\r\n        1 - 0\r\n        ',
 '\r\n        1 - 3\r\n        ',
 '\r\n        1 - 1\r\n        ',
 '\r\n        2 - 1\r\n        ',
 '\r\n        4 - 4\r\n        ',
 '\r\n        0 - 1\r\n        ',
 '\r\n        0 - 2\r\n        ',
 '\r\n        1 - 2\r\n        ',
 '\r\n        0 - 0\r\n        ',
 '\r\n        5 - 2\r\n        ',
 '\r\n        2 - 0\r\n        ',
 '\r\n        2 - 2\r\n        ',
 '\r\n        3 - 2\r\n        ',
 '\r\n        0 - 3\r\n        ',
 '\r\n        4 - 2\r\n        ',
 '\r\n        3 - 1\r\n        ',
 '\r\n        3 - 3\r\n        ',
 '\r\n        3 - 0\r\n        ',
 '\r\n        5 - 1\r\n        ',
 '\r\n        4 - 0\r\n        ',
 '\r\n        4 - 1\r\n        ',
 '\r\n        5 - 0\r\n        ',
 '\r\n        0 - 4\r\n        ',
 '\r\n        2 - 4\r\n        ',
 '\r\n        3 - 4\r\n        ',
 '\r\n        1 - 4\r\n        ',
 '\r\n        2 - 3\r\n        ',
 '\r\n        0 - 5\r\n        ',
 '\r\n        6 - 0\r\n        ',
 '\r\n        6 - 1\r\n        ',
 '\r\n        4 - 3\r\n        ',
 '\r\n        1 - 6\r\n        ',
 '\r\n        1 - 5\r\n        ',
 '\r\n        5 - 3\r\n        ',
 '\r\n        2 - 6\r\n        ']

In [32]:
dataset_definitivo_2020_2022['Goles_Visitante'] = dataset_definitivo_2020_2022['Goles_Visitante'].str.replace(",","").str.replace("\r\n","").str.replace(" ","").str.split("-")

In [33]:
lista = dataset_definitivo_2020_2022['Goles_Visitante'].tolist()
lista_goles_visitantes = []
for element in lista:
    gol_visitante="".join(map(str,element))[1]
    lista_goles_visitantes.append(gol_visitante)

In [34]:
dataset_definitivo_2020_2022['Goles_Visitante'] = lista_goles_visitantes

In [35]:
dataset_definitivo_2020_2022 = dataset_definitivo_2020_2022.drop(['Resultado'],axis=1)

### Métodos Auxiliares

In [36]:
def obtener_Puntos_Locales(dataset):
    lista_puntos_locales=[]
    goles_locales = dataset['Goles_Local'].tolist()
    goles_visitantes = dataset['Goles_Visitante'].tolist()
    for gol_local,gol_vis in zip(goles_locales,goles_visitantes):
        if(gol_local > gol_vis):
            lista_puntos_locales.append(3)
        elif(gol_local < gol_vis):
            lista_puntos_locales.append(0)
        elif(gol_local == gol_vis):
            lista_puntos_locales.append(1)
    return lista_puntos_locales

In [37]:
def obtener_Puntos_Visitantes(dataset):
    lista_puntos_visitantes=[]
    goles_locales = dataset['Goles_Local'].tolist()
    goles_visitantes = dataset['Goles_Visitante'].tolist()
    for gol_local,gol_vis in zip(goles_locales,goles_visitantes):
        if(gol_local > gol_vis):
            lista_puntos_visitantes.append(0)
        elif(gol_local < gol_vis):
            lista_puntos_visitantes.append(3)
        elif(gol_local == gol_vis):
            lista_puntos_visitantes.append(1)
    return lista_puntos_visitantes

In [38]:
def obtener_resultado(dataset):
    resultados=[]
    goles_locales = dataset['Goles_Local'].tolist()
    goles_visitantes = dataset['Goles_Visitante'].tolist()
    for gol_local,gol_vis in zip(goles_locales,goles_visitantes):
        if(gol_local > gol_vis):
            resultados.append('1')
        elif(gol_local < gol_vis):
            resultados.append('2')
        elif(gol_local == gol_vis):
            resultados.append('x')
    return resultados

In [39]:
dataset_definitivo_2020_2022['Puntos_Locales'] = obtener_Puntos_Locales(dataset_definitivo_2020_2022)

In [40]:
dataset_definitivo_2020_2022['Puntos_Visitantes'] = obtener_Puntos_Visitantes(dataset_definitivo_2020_2022)

In [41]:
dataset_definitivo_2020_2022['Resultado'] = obtener_resultado(dataset_definitivo_2020_2022)

In [42]:
dataset_definitivo_2020_2022

,Equipo_Local,Equipo_Visitante,Temporada,Goles_Local,Goles_Visitante,Puntos_Locales,Puntos_Visitantes,Resultado
0,Athletic,Barcelona,2019/2020,1,0,3,0,1
1,Celta,Real Madrid,2019/2020,1,3,0,3,2
2,Valencia,R. Sociedad,2019/2020,1,1,1,1,x
3,Mallorca,Eibar,2019/2020,2,1,3,0,1
4,Villarreal,Granada,2019/2020,4,4,1,1,x
...,...,...,...,...,...,...,...,...
375,Granada,Espanyol,2021/2022,0,0,1,1,x
376,Osasuna,Mallorca,2021/2022,0,2,0,3,2
377,Barcelona,Villarreal,2021/2022,0,2,0,3,2
378,R. Sociedad,Atlético,2021/2022,1,2,0,3,2
379,Sevilla,Athletic,2021/2022,1,0,3,0,1

In [43]:
dataset_definitivo_2020_2022.to_csv("dataset_auxiliar_Resultados_2020_2022.csv",index=False)

### Unificamos los datasets de 2015 a 2019  con el de 2020 a 2022

In [44]:
dataset_Temporada_2015_2019 =  pd.read_csv(r"dataset_auxiliar_Resultados_2015_2019.csv",sep=",");
dataset_Temporada_2015_2019

,Fecha,Equipo_Local,Equipo_Visitante,Goles_Local,Goles_Visitante,Resultado,Temporada,"Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,Bb1X2,BbMxH,BbAvH,BbMxD,BbAvD,BbMxA,BbAvA,BbOU,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA",Puntos_Locales,Puntos_Visitantes
0,21/08/15,Málaga,Sevilla,0.0,0.0,x,2015/2016,NaN,1.0,1.0
1,22/08/15,Atlético,Las Palmas,1.0,0.0,1,2015/2016,NaN,3.0,0.0
2,22/08/15,Espanyol,Getafe,1.0,0.0,1,2015/2016,NaN,3.0,0.0
3,22/08/15,Deportivo,R. Sociedad,0.0,0.0,x,2015/2016,NaN,1.0,1.0
4,22/08/15,Rayo,Valencia,0.0,0.0,x,2015/2016,NaN,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...
1515,NaN,NaN,NaN,NaN,NaN,NaN,2018/2019,"SP1,18/05/2019,Levante,Ath Madrid,2,2,D,2,0,H,...",NaN,NaN
1516,NaN,NaN,NaN,NaN,NaN,NaN,2018/2019,"SP1,18/05/2019,Sevilla,Ath Bilbao,2,0,H,1,0,H,...",NaN,NaN
1517,NaN,NaN,NaN,NaN,NaN,NaN,2018/2019,"SP1,18/05/2019,Valladolid,Valencia,0,2,A,0,1,A...",NaN,NaN
1518,NaN,NaN,NaN,NaN,NaN,NaN,2018/2019,"SP1,19/05/2019,Eibar,Barcelona,2,2,D,2,2,D,15,...",NaN,NaN
1519,NaN,NaN,NaN,NaN,NaN,NaN,2018/2019,"SP1,19/05/2019,Real Madrid,Betis,0,2,A,0,0,D,9...",NaN,NaN

In [45]:
dataset_Temporada_2020_2022 =  pd.read_csv(r"dataset_auxiliar_Resultados_2020_2022.csv",sep=",",encoding='latin-1');
dataset_Temporada_2020_2022

,Equipo_Local,Equipo_Visitante,Temporada,Goles_Local,Goles_Visitante,Puntos_Locales,Puntos_Visitantes,Resultado
0,Athletic,Barcelona,2019/2020,1,0,3,0,1
1,Celta,Real Madrid,2019/2020,1,3,0,3,2
2,Valencia,R. Sociedad,2019/2020,1,1,1,1,x
3,Mallorca,Eibar,2019/2020,2,1,3,0,1
4,Villarreal,Granada,2019/2020,4,4,1,1,x
...,...,...,...,...,...,...,...,...
1135,Granada,Espanyol,2021/2022,0,0,1,1,x
1136,Osasuna,Mallorca,2021/2022,0,2,0,3,2
1137,Barcelona,Villarreal,2021/2022,0,2,0,3,2
1138,R. Sociedad,AtlÃ©tico,2021/2022,1,2,0,3,2
1139,Sevilla,Athletic,2021/2022,1,0,3,0,1

In [46]:
dataset_Temporada_2015_2019 =  pd.read_csv(r"dataset_auxiliar_Resultados_2015_2019.csv",sep=",");
dataset_Temporada_2020_2022 =  pd.read_csv(r"dataset_auxiliar_Resultados_2020_2022.csv",sep=",");
dataset_definitivo_2015_2022 = pd.concat([dataset_Temporada_2015_2019,dataset_Temporada_2020_2022],axis=0)
dataset_definitivo_2015_2022

,Fecha,Equipo_Local,Equipo_Visitante,Goles_Local,Goles_Visitante,Resultado,Temporada,"Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,Bb1X2,BbMxH,BbAvH,BbMxD,BbAvD,BbMxA,BbAvA,BbOU,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA",Puntos_Locales,Puntos_Visitantes
0,21/08/15,Málaga,Sevilla,0.0,0.0,x,2015/2016,NaN,1.0,1.0
1,22/08/15,Atlético,Las Palmas,1.0,0.0,1,2015/2016,NaN,3.0,0.0
2,22/08/15,Espanyol,Getafe,1.0,0.0,1,2015/2016,NaN,3.0,0.0
3,22/08/15,Deportivo,R. Sociedad,0.0,0.0,x,2015/2016,NaN,1.0,1.0
4,22/08/15,Rayo,Valencia,0.0,0.0,x,2015/2016,NaN,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...
1135,NaN,Granada,Espanyol,0.0,0.0,x,2021/2022,NaN,1.0,1.0
1136,NaN,Osasuna,Mallorca,0.0,2.0,2,2021/2022,NaN,0.0,3.0
1137,NaN,Barcelona,Villarreal,0.0,2.0,2,2021/2022,NaN,0.0,3.0
1138,NaN,R. Sociedad,Atlético,1.0,2.0,2,2021/2022,NaN,0.0,3.0
1139,NaN,Sevilla,Athletic,1.0,0.0,1,2021/2022,NaN,3.0,0.0

### Añadimos las columnas de sumas acumuladas y de medias

In [47]:
dataset_definitivo_2015_2022['Suma_Goles_Locales_Acumulados']=dataset_definitivo_2015_2022['Goles_Local'].groupby(dataset_definitivo_2015_2022['Equipo_Local']).cumsum(axis=0)

dataset_definitivo_2015_2022['Media_Goles_Locales']= dataset_definitivo_2015_2022['Goles_Local'].groupby(dataset_definitivo_2015_2022['Equipo_Local']).mean()

dataset_definitivo_2015_2022['Suma_Goles_Visitantes_Acumulados']= dataset_definitivo_2015_2022['Goles_Visitante'].groupby(dataset_definitivo_2015_2022['Equipo_Visitante']).cumsum(axis=0)

dataset_definitivo_2015_2022['Media_Goles_Visitantes']= dataset_definitivo_2015_2022['Goles_Visitante'].groupby(dataset_definitivo_2015_2022['Equipo_Visitante']).mean()

dataset_definitivo_2015_2022['Media_Puntos_Locales']= dataset_definitivo_2015_2022['Puntos_Locales'].groupby(dataset_definitivo_2015_2022['Equipo_Local']).mean()

dataset_definitivo_2015_2022['Puntos_Locales_Acumulados']= dataset_definitivo_2015_2022['Puntos_Locales'].groupby(dataset_definitivo_2015_2022['Equipo_Local']).cumsum(axis=0)

dataset_definitivo_2015_2022['Media_Puntos_Visitantes']= dataset_definitivo_2015_2022['Puntos_Visitantes'].groupby(dataset_definitivo_2015_2022['Equipo_Visitante']).mean()

dataset_definitivo_2015_2022['Puntos_Visitantes_Acumulados']= dataset_definitivo_2015_2022['Puntos_Visitantes'].groupby(dataset_definitivo_2015_2022['Equipo_Visitante']).cumsum(axis=0)

In [48]:
dataset_definitivo_2015_2022

,Fecha,Equipo_Local,Equipo_Visitante,Goles_Local,Goles_Visitante,Resultado,Temporada,"Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,Bb1X2,BbMxH,BbAvH,BbMxD,BbAvD,BbMxA,BbAvA,BbOU,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA",Puntos_Locales,Puntos_Visitantes,Suma_Goles_Locales_Acumulados,Media_Goles_Locales,Suma_Goles_Visitantes_Acumulados,Media_Goles_Visitantes,Media_Puntos_Locales,Puntos_Locales_Acumulados,Media_Puntos_Visitantes,Puntos_Visitantes_Acumulados
0,21/08/15,Málaga,Sevilla,0.0,0.0,x,2015/2016,NaN,1.0,1.0,0.0,NaN,0.0,NaN,NaN,1.0,NaN,1.0
1,22/08/15,Atlético,Las Palmas,1.0,0.0,1,2015/2016,NaN,3.0,0.0,1.0,NaN,0.0,NaN,NaN,3.0,NaN,0.0
2,22/08/15,Espanyol,Getafe,1.0,0.0,1,2015/2016,NaN,3.0,0.0,1.0,NaN,0.0,NaN,NaN,3.0,NaN,0.0
3,22/08/15,Deportivo,R. Sociedad,0.0,0.0,x,2015/2016,NaN,1.0,1.0,0.0,NaN,0.0,NaN,NaN,1.0,NaN,1.0
4,22/08/15,Rayo,Valencia,0.0,0.0,x,2015/2016,NaN,1.0,1.0,0.0,NaN,0.0,NaN,NaN,1.0,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1135,NaN,Granada,Espanyol,0.0,0.0,x,2021/2022,NaN,1.0,1.0,116.0,NaN,82.0,NaN,NaN,125.0,NaN,79.0
1136,NaN,Osasuna,Mallorca,0.0,2.0,2,2021/2022,NaN,0.0,3.0,87.0,NaN,31.0,NaN,NaN,89.0,NaN,18.0
1137,NaN,Barcelona,Villarreal,0.0,2.0,2,2021/2022,NaN,0.0,3.0,317.0,NaN,141.0,NaN,NaN,274.0,NaN,158.0
1138,NaN,R. Sociedad,Atlético,1.0,2.0,2,2021/2022,NaN,0.0,3.0,182.0,NaN,169.0,NaN,NaN,193.0,NaN,207.0
1139,NaN,Sevilla,Athletic,1.0,0.0,1,2021/2022,NaN,3.0,0.0,197.0,NaN,113.0,NaN,NaN,249.0,NaN,119.0

### Vamos a dividir en Locales y Visitantes

In [49]:
dfLocales= pd.DataFrame()
dfLocales['Fecha']= dataset_definitivo_2015_2022['Fecha']
dfLocales['Equipo']= dataset_definitivo_2015_2022['Equipo_Local']
dfLocales['Goles_Local']= dataset_definitivo_2015_2022['Goles_Local']
dfLocales['Local/Visitante']= 'Local'
dfLocales['Temporada'] = dataset_definitivo_2015_2022['Temporada']
dfLocales['Suma_Goles_Locales_Acumulados'] = dataset_definitivo_2015_2022['Suma_Goles_Locales_Acumulados']
dfLocales['Media_Goles_Locales'] = dataset_definitivo_2015_2022['Media_Goles_Locales']
dfLocales['Puntos_Locales'] = dataset_definitivo_2015_2022['Puntos_Locales']
dfLocales['Media_Puntos_Locales'] = dataset_definitivo_2015_2022['Media_Puntos_Locales']
dfLocales['Puntos_Locales_Acumulados'] = dataset_definitivo_2015_2022['Puntos_Locales_Acumulados']
dfLocales['Resultado'] = dataset_definitivo_2015_2022['Resultado']

In [50]:
dfVisitantes= pd.DataFrame()
dfVisitantes['Fecha']= dataset_definitivo_2015_2022['Fecha']
dfVisitantes['Equipo']= dataset_definitivo_2015_2022['Equipo_Visitante']
dfVisitantes['Goles_Visitante']= dataset_definitivo_2015_2022['Goles_Visitante']
dfVisitantes['Local/Visitante']= 'Visitante'
dfVisitantes['Temporada'] = dataset_definitivo_2015_2022['Temporada']
dfVisitantes['Suma_Goles_Visitantes_Acumulados'] = dataset_definitivo_2015_2022['Suma_Goles_Visitantes_Acumulados']
dfVisitantes['Media_Goles_Visitantes'] = dataset_definitivo_2015_2022['Media_Goles_Visitantes']
dfVisitantes['Puntos_Visitantes'] = dataset_definitivo_2015_2022['Puntos_Visitantes']
dfVisitantes['Media_Puntos_Visitantes'] = dataset_definitivo_2015_2022['Media_Puntos_Visitantes']
dfVisitantes['Puntos_Visitantes_Acumulados'] = dataset_definitivo_2015_2022['Puntos_Visitantes_Acumulados']
dfVisitantes['Resultado'] = dataset_definitivo_2015_2022['Resultado']

### Unificamos los 2 DataFrames y montamos el dataset Definitivo

In [51]:
dataset_definitivo_combinado_2015_2022 = pd.concat([dfLocales,dfVisitantes],axis=0)
dataset_definitivo_combinado_2015_2022

,Fecha,Equipo,Goles_Local,Local/Visitante,Temporada,Suma_Goles_Locales_Acumulados,Media_Goles_Locales,Puntos_Locales,Media_Puntos_Locales,Puntos_Locales_Acumulados,Resultado,Goles_Visitante,Suma_Goles_Visitantes_Acumulados,Media_Goles_Visitantes,Puntos_Visitantes,Media_Puntos_Visitantes,Puntos_Visitantes_Acumulados
0,21/08/15,Málaga,0.0,Local,2015/2016,0.0,NaN,1.0,NaN,1.0,x,NaN,NaN,NaN,NaN,NaN,NaN
1,22/08/15,Atlético,1.0,Local,2015/2016,1.0,NaN,3.0,NaN,3.0,1,NaN,NaN,NaN,NaN,NaN,NaN
2,22/08/15,Espanyol,1.0,Local,2015/2016,1.0,NaN,3.0,NaN,3.0,1,NaN,NaN,NaN,NaN,NaN,NaN
3,22/08/15,Deportivo,0.0,Local,2015/2016,0.0,NaN,1.0,NaN,1.0,x,NaN,NaN,NaN,NaN,NaN,NaN
4,22/08/15,Rayo,0.0,Local,2015/2016,0.0,NaN,1.0,NaN,1.0,x,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1135,NaN,Espanyol,NaN,Visitante,2021/2022,NaN,NaN,NaN,NaN,NaN,x,0.0,82.0,NaN,1.0,NaN,79.0
1136,NaN,Mallorca,NaN,Visitante,2021/2022,NaN,NaN,NaN,NaN,NaN,2,2.0,31.0,NaN,3.0,NaN,18.0
1137,NaN,Villarreal,NaN,Visitante,2021/2022,NaN,NaN,NaN,NaN,NaN,2,2.0,141.0,NaN,3.0,NaN,158.0
1138,NaN,Atlético,NaN,Visitante,2021/2022,NaN,NaN,NaN,NaN,NaN,2,2.0,169.0,NaN,3.0,NaN,207.0
1139,NaN,Athletic,NaN,Visitante,2021/2022,NaN,NaN,NaN,NaN,NaN,1,0.0,113.0,NaN,0.0,NaN,119.0

### Arreglamos Aquellos Valores Nulos

In [52]:
from numpy import nan
dataset_definitivo_combinado_2015_2022['Fecha'].replace({nan:'Desconocida'},inplace=True)
dataset_definitivo_combinado_2015_2022['Goles_Local'].replace({nan:0},inplace=True)
dataset_definitivo_combinado_2015_2022['Goles_Visitante'].replace({nan:0},inplace=True)
dataset_definitivo_combinado_2015_2022['Puntos_Locales'].replace({nan:0},inplace=True)
dataset_definitivo_combinado_2015_2022['Puntos_Visitantes'].replace({nan:0},inplace=True)
dataset_definitivo_combinado_2015_2022['Suma_Goles_Locales_Acumulados'].replace({nan:0},inplace=True)
dataset_definitivo_combinado_2015_2022['Suma_Goles_Visitantes_Acumulados'].replace({nan:0},inplace=True)
dataset_definitivo_combinado_2015_2022['Puntos_Locales_Acumulados'].replace({nan:0},inplace=True)
dataset_definitivo_combinado_2015_2022['Puntos_Visitantes_Acumulados'].replace({nan:0},inplace=True)
dataset_definitivo_combinado_2015_2022['Media_Goles_Locales'].replace({nan:0},inplace=True)
dataset_definitivo_combinado_2015_2022['Media_Goles_Visitantes'].replace({nan:0},inplace=True)
dataset_definitivo_combinado_2015_2022['Media_Puntos_Locales'].replace({nan:0},inplace=True)
dataset_definitivo_combinado_2015_2022['Media_Puntos_Visitantes'].replace({nan:0},inplace=True)

In [53]:
dataset_definitivo_combinado_2015_2022

,Fecha,Equipo,Goles_Local,Local/Visitante,Temporada,Suma_Goles_Locales_Acumulados,Media_Goles_Locales,Puntos_Locales,Media_Puntos_Locales,Puntos_Locales_Acumulados,Resultado,Goles_Visitante,Suma_Goles_Visitantes_Acumulados,Media_Goles_Visitantes,Puntos_Visitantes,Media_Puntos_Visitantes,Puntos_Visitantes_Acumulados
0,21/08/15,Málaga,0.0,Local,2015/2016,0.0,0.0,1.0,0.0,1.0,x,0.0,0.0,0.0,0.0,0.0,0.0
1,22/08/15,Atlético,1.0,Local,2015/2016,1.0,0.0,3.0,0.0,3.0,1,0.0,0.0,0.0,0.0,0.0,0.0
2,22/08/15,Espanyol,1.0,Local,2015/2016,1.0,0.0,3.0,0.0,3.0,1,0.0,0.0,0.0,0.0,0.0,0.0
3,22/08/15,Deportivo,0.0,Local,2015/2016,0.0,0.0,1.0,0.0,1.0,x,0.0,0.0,0.0,0.0,0.0,0.0
4,22/08/15,Rayo,0.0,Local,2015/2016,0.0,0.0,1.0,0.0,1.0,x,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1135,Desconocida,Espanyol,0.0,Visitante,2021/2022,0.0,0.0,0.0,0.0,0.0,x,0.0,82.0,0.0,1.0,0.0,79.0
1136,Desconocida,Mallorca,0.0,Visitante,2021/2022,0.0,0.0,0.0,0.0,0.0,2,2.0,31.0,0.0,3.0,0.0,18.0
1137,Desconocida,Villarreal,0.0,Visitante,2021/2022,0.0,0.0,0.0,0.0,0.0,2,2.0,141.0,0.0,3.0,0.0,158.0
1138,Desconocida,Atlético,0.0,Visitante,2021/2022,0.0,0.0,0.0,0.0,0.0,2,2.0,169.0,0.0,3.0,0.0,207.0
1139,Desconocida,Athletic,0.0,Visitante,2021/2022,0.0,0.0,0.0,0.0,0.0,1,0.0,113.0,0.0,0.0,0.0,119.0